service: imgur-clone-functions

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  bucket: imgur-serverless

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  # uploadjs:
  #   handler: functions/upload-node.upload
  #   runtime: nodejs6.10
  #   events:
  #     - http:
  #         path: upload-node
  #         method: post
  #         cors: true
  #         authorizer:
  #           arn: arn:aws:cognito-idp:eu-west-1:853957954650:userpool/eu-west-1_9IBAarCx9
  #           identitySource: method.request.header.Authorization
  #           type: token

  list:
    handler: functions/list.list
    events:
      - http:
          path: list
          method: get
          cors: true
  
  single:
    handler: functions/single.single
    events:
      - http:
          path: single
          method: get
          cors: true

